#include <inkview.h>
#include <dirent.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/statvfs.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

#define ROOT "/mnt/ext1/system/config/helciny-podcasty"
#define AUDIO_DIR "/mnt/ext1/Podcasts"
#define CACHE_DIR AUDIO_DIR "/HelcinyPodcasty"
#define DATA ROOT "/catalog.dat"
#define CFG ROOT "/settings"
#define IMAGE_CACHE_V2 ROOT "/images-v2"
#define AUDIO_PART AUDIO_DIR "/HelcinyPodcasty.part"
#define DEBUG_LOG ROOT "/playback.log"
#define CONTROL_FILE ROOT "/control"
#define POSITION_FILE ROOT "/position"
#define WORKER "/mnt/ext1/applications/HelcinyAlsaWorker.bin"
#define WORKER_LIBS "/mnt/ext1/applications/HelcinyAlsaWorker-libs"
#define BASE "http://38.19.198.69:8093/podcasts/"
#define MAXE 180
#define PAGE_SIZE 4
#define PROGRESS_Y 510
typedef struct { char feed[16],key[20],title[160],date[40],duration[16],image[80],audio[700]; } Episode;
static Episode ep[MAXE]; static int count,view,feed,page,autoplay,current_audio=-1,paused,volume=70,stop_requested,position_sec,duration_sec; static ifont *f_title,*f_body,*f_small;
static pid_t download_pid=-1; static int pending_audio=-1,play_after_download,bulk_download,bulk_feed,bulk_done,bulk_total;
static pid_t player_pid=-1;
static char status_text[100]="";
static const char *feed_ids[]={"karlik","minecraft","otazky"};
static const char *feed_names[]={"Karlikovy minecrafticke pohadky","Minecraft pribehy na dobrou noc","Same otazky"};
static void repaint(void);
static int wake_network(void);
static int valid_mp3(const char*path);
static void playback_log(const char*s){FILE*f=fopen(DEBUG_LOG,"a");if(f){fprintf(f,"%ld %s\n",(long)time(NULL),s);fflush(f);fsync(fileno(f));fclose(f);}}

static void txt(int x,int y,int w,int h,const char*s,ifont*f,int flags){SetFont(f,BLACK);DrawTextRect(x,y,w,h,s,flags|DOTS);}
static void btn(int x,int y,int w,int h,const char*s,int dark){if(dark){FillArea(x,y,w,h,BLACK);SetFont(f_body,WHITE);}else{DrawRect(x,y,w,h,BLACK);SetFont(f_body,BLACK);}DrawTextRect(x,y+8,w,h-12,s,ALIGN_CENTER|VALIGN_MIDDLE);}
static int hit(int x,int y,int bx,int by,int bw,int bh){return x>=bx&&x<bx+bw&&y>=by&&y<by+bh;}
static void mkdirs(void){mkdir(ROOT,0777);mkdir(ROOT "/images",0777);mkdir(AUDIO_DIR,0777);mkdir(CACHE_DIR,0777);}
static void cleanup_orphan_player(void){DIR*d=opendir("/proc");struct dirent*de;char path[80],cmd[300];FILE*f;if(d){while((de=readdir(d))){pid_t pid=(pid_t)atoi(de->d_name);size_t n;if(pid<=1)continue;snprintf(path,sizeof path,"/proc/%d/cmdline",(int)pid);f=fopen(path,"r");if(!f)continue;n=fread(cmd,1,sizeof(cmd)-1,f);fclose(f);cmd[n]=0;if(strstr(cmd,"HelcinyAlsaWorker.bin"))kill(pid,SIGTERM);}closedir(d);usleep(250000);}remove(CONTROL_FILE);remove(POSITION_FILE);iv_sleepmode(1);SetAutoPowerOff(1);}
static void migrate_image_cache(void){DIR*d;struct dirent*de;char path[400];FILE*f;if(!access(IMAGE_CACHE_V2,R_OK))return;d=opendir(ROOT "/images");if(d){while((de=readdir(d)))if(strstr(de->d_name,".jpg")){snprintf(path,sizeof path,ROOT "/images/%s",de->d_name);remove(path);}closedir(d);}f=fopen(IMAGE_CACHE_V2,"w");if(f){fputs("2\n",f);fclose(f);}}
static void save_cfg(void){FILE*f=fopen(CFG,"w");if(f){fprintf(f,"%d %d\n",autoplay,volume);fclose(f);}}
static void load_cfg(void){FILE*f=fopen(CFG,"r");if(f){fscanf(f,"%d %d",&autoplay,&volume);fclose(f);}if(volume<0||volume>100)volume=70;}
static int split(char*s,char**v,int max){int n=0;while(n<max&&(v[n]=strsep(&s,"|"))!=NULL)n++;return n;}
static int load_catalog(void){FILE*f=fopen(DATA,"r");char line[2048];count=0;if(!f)return 0;while(fgets(line,sizeof line,f)){char*p[10];int complete=strchr(line,'\n')||feof(f);if(!complete){while(fgets(line,sizeof line,f)&&!strchr(line,'\n')){}continue;}line[strcspn(line,"\r\n")]=0;if(line[0]!='E'||split(line,p,10)<8||count>=MAXE)continue;if(strncmp(p[7],"http://",7)&&strncmp(p[7],"https://",8))continue;Episode*e=&ep[count++];snprintf(e->feed,sizeof e->feed,"%s",p[1]);snprintf(e->key,sizeof e->key,"%s",p[2]);snprintf(e->title,sizeof e->title,"%s",p[3]);snprintf(e->date,sizeof e->date,"%s",p[4]);snprintf(e->duration,sizeof e->duration,"%s",p[5]);snprintf(e->image,sizeof e->image,"%s",p[6]);snprintf(e->audio,sizeof e->audio,"%s",p[7]);}fclose(f);return count;}
static void refresh(void){int rc;char cmd[1200],url[300];mkdirs();FillArea(35,95,ScreenWidth()-70,55,WHITE);txt(40,100,ScreenWidth()-80,42,"Obnovuji katalog pres WiFi...",f_small,ALIGN_LEFT);PartialUpdate(35,95,ScreenWidth()-70,55);rc=wake_network();if(rc!=NET_OK){snprintf(status_text,sizeof status_text,"WiFi nelze pripojit, kod %d.",rc);return;}snprintf(url,sizeof url,"%scatalog.dat",BASE);snprintf(cmd,sizeof cmd,"rm -f '%s.tmp'; (/bin/busybox wget -q -T 30 -O '%s.tmp' '%s' || /usr/bin/wget -q -T 30 -O '%s.tmp' '%s' || wget -q -T 30 -O '%s.tmp' '%s')",DATA,DATA,url,DATA,url,DATA,url);remove(DATA ".tmp");rc=DownloadTo(0,url,NULL,DATA ".tmp",30);if(rc!=NET_OK)rc=system(cmd);if(!rc&&access(DATA ".tmp",R_OK)==0)rename(DATA ".tmp",DATA);else rc=-1;if(rc)snprintf(status_text,sizeof status_text,"Obnova selhala. Zkontroluj WiFi.");else if(!load_catalog())snprintf(status_text,sizeof status_text,"Stazeny katalog je poskozeny.");else snprintf(status_text,sizeof status_text,"Katalog byl uspesne obnoven.");}
static int indices(int*out){int i,n=0,start=page*PAGE_SIZE;for(i=0;i<count;i++)if(!strcmp(ep[i].feed,feed_ids[feed])){if(n>=start&&n<start+PAGE_SIZE)out[n-start]=i;n++;}return n;}
static void episode_path(int idx,char*path,size_t size){snprintf(path,size,"%s/%s.mp3",CACHE_DIR,ep[idx].key);}
static int episode_cached(int idx){char path[300];struct stat st;episode_path(idx,path,sizeof path);return !stat(path,&st)&&st.st_size>1024&&valid_mp3(path);}
static int feed_cache_count(int selected_feed,int*total){int i,cached=0;*total=0;for(i=0;i<count;i++)if(!strcmp(ep[i].feed,feed_ids[selected_feed])){(*total)++;if(episode_cached(i))cached++;}return cached;}
static int enough_space(void){struct statvfs fs;if(statvfs(AUDIO_DIR,&fs))return 1;return (unsigned long long)fs.f_bavail*fs.f_frsize>200ULL*1024*1024;}
static void fetch_image(Episode*e){char path[300],url[400],cmd[1400];struct stat st;int rc;if(!e->image[0])return;snprintf(path,sizeof path,ROOT "/images/%s.jpg",e->key);if(!stat(path,&st)&&st.st_size>200)return;remove(path);snprintf(url,sizeof url,"%s%s",BASE,e->image);remove(strcat(strcpy(cmd,path),".tmp"));rc=DownloadTo(0,url,NULL,cmd,15);if(rc!=NET_OK){snprintf(cmd,sizeof cmd,"/bin/busybox wget -q -T 15 -O '%s.tmp' '%s' && mv '%s.tmp' '%s'",path,url,path,path);system(cmd);}else rename(cmd,path);}
static void prepare_page_images(void){int ids[PAGE_SIZE],total=indices(ids),shown=total-page*PAGE_SIZE,i;if(shown>PAGE_SIZE)shown=PAGE_SIZE;for(i=0;i<shown;i++)fetch_image(&ep[ids[i]]);}
static void draw_home(void){int w=ScreenWidth(),i;txt(40,30,w-80,65,"Helciny podcasty",f_title,ALIGN_LEFT);txt(40,100,w-80,42,"Online poslech pres WiFi",f_small,ALIGN_LEFT);for(i=0;i<3;i++)btn(55,170+i*98,w-110,88,feed_names[i],0);btn(55,480,w-110,88,autoplay?"Dalsi dil: ZAPNUTO":"Dalsi dil: VYPNUTO",autoplay);btn(55,578,w-110,88,"OBNOVIT KATALOG",0);if(player_pid>0)btn(55,690,w-110,88,"NYNI HRAJE",1);if(status_text[0])txt(55,800,w-110,55,status_text,f_small,ALIGN_CENTER);}
static void draw_list(void){int w=ScreenWidth(),ids[PAGE_SIZE],total=indices(ids),shown=total-page*PAGE_SIZE,i,cached,feed_total;char s[100];if(shown>PAGE_SIZE)shown=PAGE_SIZE;cached=feed_cache_count(feed,&feed_total);txt(35,25,w-70,55,feed_names[feed],f_title,ALIGN_LEFT);snprintf(s,sizeof s,"Epizody %d-%d z %d   Ulozeno %d/%d",page*PAGE_SIZE+1,page*PAGE_SIZE+shown,total,cached,feed_total);txt(38,82,w-76,38,s,f_small,ALIGN_LEFT);for(i=0;i<shown;i++){Episode*e=&ep[ids[i]];int y=130+i*260;char path[300],meta[100];snprintf(path,sizeof path,ROOT "/images/%s.jpg",e->key);ibitmap*bm=LoadJPEG(path,250,250,100,100,1);DrawRect(40,y,250,250,BLACK);if(bm){DrawBitmap(40,y,bm);free(bm);}else remove(path);txt(320,y+25,w-360,135,e->title,f_body,ALIGN_LEFT|VALIGN_MIDDLE);snprintf(meta,sizeof meta,"%s   %s   %s",e->duration,e->date,episode_cached(ids[i])?"ULOZENO":"ONLINE");txt(320,y+175,w-360,45,meta,f_small,ALIGN_LEFT);DrawLine(40,y+252,w-40,y+252,BLACK);}btn(35,1180,175,80,"ZPET",0);btn(235,1180,w-680,80,player_pid>0?"NYNI HRAJE":"DOPLNIT DILY",player_pid>0||bulk_download);btn(w-420,1180,175,80,"<",0);btn(w-220,1180,175,80,">",0);}
static int parse_duration(const char*s){int a=0,b=0,c=0;if(sscanf(s,"%d:%d:%d",&a,&b,&c)==3)return a*3600+b*60+c;if(sscanf(s,"%d:%d",&a,&b)==2)return a*60+b;if(sscanf(s,"%d",&a)==1)return a;return 0;}
static void draw_progress(void){int w=ScreenWidth(),barw=w-140,fill=duration_sec>0?(int)((long)barw*position_sec/duration_sec):0;char s[80];if(fill<0)fill=0;if(fill>barw)fill=barw;FillArea(55,PROGRESS_Y,w-110,72,WHITE);DrawRect(70,PROGRESS_Y+5,barw,28,BLACK);if(fill>2)FillArea(72,PROGRESS_Y+7,fill-2,24,BLACK);snprintf(s,sizeof s,"%d:%02d / %d:%02d",position_sec/60,position_sec%60,duration_sec/60,duration_sec%60);txt(70,PROGRESS_Y+37,barw,32,s,f_small,ALIGN_CENTER);}
static void draw_player(void){int w=ScreenWidth();char s[80],path[300];ibitmap*bm=NULL;txt(40,25,w-80,60,"Nyni hraje",f_title,ALIGN_CENTER);if(current_audio>=0){snprintf(path,sizeof path,ROOT "/images/%s.jpg",ep[current_audio].key);bm=LoadJPEG(path,240,240,100,100,1);DrawRect((w-240)/2,95,240,240,BLACK);if(bm){DrawBitmap((w-240)/2,95,bm);free(bm);}txt(50,350,w-100,135,ep[current_audio].title,f_body,ALIGN_CENTER|VALIGN_MIDDLE);}draw_progress();btn(70,600,w-140,95,paused?"POKRACOVAT":"PAUZA",paused);snprintf(s,sizeof s,"HLASITOST  %d %%",volume);txt(60,720,w-120,50,s,f_body,ALIGN_CENTER);btn(70,785,180,85,"-",0);btn(w-250,785,180,85,"+",0);btn(70,910,w-140,95,"ZASTAVIT",0);btn(70,1040,w-140,90,autoplay?"DALSI DIL: ZAPNUTO":"DALSI DIL: VYPNUTO",autoplay);btn(70,1170,w-140,85,"ZPET K EPIZODAM",0);}
static int valid_mp3(const char*path){unsigned char b[3];FILE*f=fopen(path,"rb");if(!f)return 0;if(fread(b,1,3,f)!=3){fclose(f);return 0;}fclose(f);return !memcmp(b,"ID3",3)||(b[0]==0xff&&(b[1]&0xe0)==0xe0);}
static int wake_network(void){int state=QueryNetwork(),rc=NET_OK;char msg[100];if((state&NET_CONNECTED)!=NET_CONNECTED)rc=NetConnect(NULL);state=QueryNetwork();snprintf(msg,sizeof msg,"WiFi state=%x connect=%d",state,rc);playback_log(msg);return rc==NET_OK&&(state&NET_CONNECTED)==NET_CONNECTED?NET_OK:(rc==NET_OK?NET_ENETWORK:rc);}
static void poll_player(void);
static void bulk_next(void);
static void start_player(void){char command[1200],vol[8],audio_path[300];if(player_pid>0||current_audio<0)return;episode_path(current_audio,audio_path,sizeof audio_path);snprintf(vol,sizeof vol,"%d",volume);snprintf(command,sizeof command,"exec env LD_LIBRARY_PATH='/ebrmain/lib:/ebrmain/cramfs/lib:/usr/local/lib:/usr/lib:/lib:%s' '%s' '%s' '%s' >>'%s' 2>&1",WORKER_LIBS,WORKER,audio_path,vol,DEBUG_LOG);stop_requested=0;paused=0;position_sec=0;duration_sec=parse_duration(ep[current_audio].duration);remove(CONTROL_FILE);remove(POSITION_FILE);iv_sleepmode(0);SetAutoPowerOff(0);player_pid=fork();if(player_pid==0){execl("/bin/sh","sh","-c",command,(char*)NULL);_exit(127);}if(player_pid<0){iv_sleepmode(1);SetAutoPowerOff(1);snprintf(status_text,sizeof status_text,"Prehravac nelze spustit.");repaint();return;}playback_log("05 ALSA player started");view=2;repaint();SetWeakTimer("podcast-player",poll_player,500);}
static void finish_download(void){int status;char msg[120],target[300];struct stat st;pid_t done=waitpid(download_pid,&status,WNOHANG);if(done==0){SetWeakTimer("podcast-download",finish_download,1000);return;}download_pid=-1;if(done<0||!WIFEXITED(status)||WEXITSTATUS(status)||stat(AUDIO_PART,&st)||st.st_size<1024||!valid_mp3(AUDIO_PART)){remove(AUDIO_PART);playback_log("03 download failed");if(bulk_download)snprintf(status_text,sizeof status_text,"Stahovani selhalo u dilu %d/%d.",bulk_done+1,bulk_total);else snprintf(status_text,sizeof status_text,"Epizodu se nepodarilo nacist.");bulk_download=0;repaint();return;}snprintf(msg,sizeof msg,"03 valid mp3 bytes=%ld",(long)st.st_size);playback_log(msg);episode_path(pending_audio,target,sizeof target);remove(target);if(rename(AUDIO_PART,target)){playback_log("04 rename failed");bulk_download=0;snprintf(status_text,sizeof status_text,"Stazeny soubor nelze ulozit.");repaint();return;}playback_log("04 cached file ready");if(play_after_download){current_audio=pending_audio;start_player();}else{bulk_done++;bulk_next();}}
static void download_index(int idx,int play_after){char cmd[1900];int net;if(idx<0||idx>=count||download_pid>0)return;if(!enough_space()){bulk_download=0;snprintf(status_text,sizeof status_text,"Malo mista. Ponechavam rezervu 200 MB.");repaint();return;}net=wake_network();if(net!=NET_OK){bulk_download=0;snprintf(status_text,sizeof status_text,"WiFi nelze pripojit, kod %d.",net);repaint();return;}remove(AUDIO_PART);snprintf(cmd,sizeof cmd,"(/bin/busybox wget -q -T 600 -O '%s' '%s' || /usr/bin/wget -q -T 600 -O '%s' '%s' || wget -q -T 600 -O '%s' '%s') 2>>'%s'",AUDIO_PART,ep[idx].audio,AUDIO_PART,ep[idx].audio,AUDIO_PART,ep[idx].audio,DEBUG_LOG);pending_audio=idx;play_after_download=play_after;download_pid=fork();if(download_pid==0){setpgid(0,0);execl("/bin/sh","sh","-c",cmd,(char*)NULL);_exit(127);}if(download_pid<0){bulk_download=0;snprintf(status_text,sizeof status_text,"Stahovani nelze spustit.");repaint();return;}setpgid(download_pid,download_pid);SetWeakTimer("podcast-download",finish_download,1000);}
static void play_index(int idx){if(idx<0||idx>=count||download_pid>0)return;if(player_pid>0){snprintf(status_text,sizeof status_text,"Nejprve zastav prehravanou epizodu.");repaint();return;}if(episode_cached(idx)){current_audio=idx;start_player();return;}snprintf(status_text,sizeof status_text,"Stahuji vybranou epizodu...");repaint();download_index(idx,1);}
static void bulk_next(void){int i;if(!bulk_download)return;for(i=0;i<count;i++)if(!strcmp(ep[i].feed,feed_ids[bulk_feed])&&!episode_cached(i)){snprintf(status_text,sizeof status_text,"Stahuji %d z %d...",bulk_done+1,bulk_total);repaint();download_index(i,0);return;}bulk_download=0;snprintf(status_text,sizeof status_text,"Vsechny epizody jsou ulozene.");repaint();}
static void start_bulk_download(void){int i;if(download_pid>0||player_pid>0)return;bulk_feed=feed;bulk_done=0;bulk_total=0;for(i=0;i<count;i++)if(!strcmp(ep[i].feed,feed_ids[feed])&&!episode_cached(i))bulk_total++;if(!bulk_total){snprintf(status_text,sizeof status_text,"Vsechny epizody uz jsou ulozene.");repaint();return;}bulk_download=1;remove(DEBUG_LOG);bulk_next();}
static void play_episode(int selected){int ids[PAGE_SIZE],total=indices(ids);if(selected<0||selected>=PAGE_SIZE||page*PAGE_SIZE+selected>=total)return;play_index(ids[selected]);}
static int next_episode(void){int i;if(current_audio<0)return -1;for(i=current_audio+1;i<count;i++)if(!strcmp(ep[i].feed,ep[current_audio].feed))return i;return -1;}
static void poll_player(void){int status,pos,total,old=position_sec;pid_t done;FILE*f;if(player_pid<=0)return;f=fopen(POSITION_FILE,"r");if(f){if(fscanf(f,"%d %d",&pos,&total)==2){position_sec=pos;if(total>0)duration_sec=total;}fclose(f);}if(view==2&&position_sec!=old){draw_progress();PartialUpdate(55,PROGRESS_Y,ScreenWidth()-110,72);}done=waitpid(player_pid,&status,WNOHANG);if(done==0){SetWeakTimer("podcast-player",poll_player,500);return;}player_pid=-1;paused=0;iv_sleepmode(1);SetAutoPowerOff(1);if(!stop_requested&&done>0&&WIFEXITED(status)&&WEXITSTATUS(status)==0&&autoplay){int next=next_episode();if(next>=0&&episode_cached(next)){snprintf(status_text,sizeof status_text,"Spoustim nasledujici ulozeny dil...");play_index(next);return;}if(next>=0)snprintf(status_text,sizeof status_text,"Dalsi dil neni ulozeny.");}if(view==2){if(!status_text[0])snprintf(status_text,sizeof status_text,stop_requested?"Prehravani zastaveno.":"Epizoda dohrala.");view=1;repaint();}}
static void repaint(void){ClearScreen();if(view==0)draw_home();else if(view==1)draw_list();else draw_player();FullUpdate();}
static void player_command(char command,int value){FILE*f=fopen(CONTROL_FILE,"w");if(f){fprintf(f,"%c %d\n",command,value);fclose(f);}}
static void seek_to(int x){int w=ScreenWidth();if(duration_sec<=0)return;position_sec=(int)((long)(x-70)*duration_sec/(w-140));if(position_sec<0)position_sec=0;if(position_sec>duration_sec)position_sec=duration_sec;player_command('S',position_sec);draw_progress();PartialUpdate(55,PROGRESS_Y,w-110,72);}
static void touch(int x,int y){int w=ScreenWidth(),i;if(view==0){for(i=0;i<3;i++)if(hit(x,y,55,170+i*98,w-110,88)){feed=i;page=0;view=1;prepare_page_images();repaint();return;}if(hit(x,y,55,480,w-110,88)){autoplay=!autoplay;save_cfg();repaint();}else if(hit(x,y,55,578,w-110,88)){refresh();repaint();}else if(player_pid>0&&hit(x,y,55,690,w-110,88)){view=2;repaint();}}else if(view==1){if(y>=130&&y<1170&&x>=40&&x<w-40&&(y-130)%260<250){i=(y-130)/260;if(i<PAGE_SIZE)play_episode(i);}else if(hit(x,y,35,1165,190,110)){view=0;repaint();}else if(hit(x,y,235,1165,w-680,110)){if(player_pid>0){view=2;repaint();}else start_bulk_download();}else if(hit(x,y,w-430,1165,190,110)&&page>0){page--;prepare_page_images();repaint();}else if(hit(x,y,w-230,1165,200,110)){int ids[PAGE_SIZE];if((page+1)*PAGE_SIZE<indices(ids)){page++;prepare_page_images();repaint();}}}else{if(hit(x,y,70,PROGRESS_Y-10,w-140,80)&&player_pid>0){seek_to(x);}else if(hit(x,y,70,600,w-140,95)&&player_pid>0){player_command('P',0);paused=!paused;repaint();}else if(hit(x,y,70,785,180,85)&&player_pid>0&&volume>0){volume-=10;player_command('V',volume);save_cfg();repaint();}else if(hit(x,y,w-250,785,180,85)&&player_pid>0&&volume<100){volume+=10;player_command('V',volume);save_cfg();repaint();}else if(hit(x,y,70,910,w-140,95)&&player_pid>0){stop_requested=1;player_command('Q',0);}else if(hit(x,y,70,1040,w-140,90)){autoplay=!autoplay;save_cfg();repaint();}else if(hit(x,y,70,1170,w-140,85)){view=1;repaint();}}}
static int handler(int type,int p1,int p2){if(type==EVT_INIT){f_title=OpenFont(DEFAULTFONTB,42,1);f_body=OpenFont(DEFAULTFONT,30,1);f_small=OpenFont(DEFAULTFONT,23,1);mkdirs();cleanup_orphan_player();migrate_image_cache();load_cfg();load_catalog();repaint();}else if(type==EVT_REPAINT)repaint();else if(type==EVT_POINTERUP)touch(p1,p2);else if(type==EVT_KEYDOWN&&p1==IV_KEY_BACK){if(view==2){view=1;repaint();}else if(view){view=0;repaint();}else CloseApp();}else if(type==EVT_EXIT){if(download_pid>0){kill(-download_pid,SIGTERM);waitpid(download_pid,NULL,0);remove(AUDIO_PART);}if(player_pid>0)kill(player_pid,SIGTERM);iv_sleepmode(1);SetAutoPowerOff(1);CloseFont(f_title);CloseFont(f_body);CloseFont(f_small);}return 0;}
int main(void){InkViewMain(handler);return 0;}
