#include <inkview.h>
#include <dirent.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

#define ROOT "/mnt/ext1/system/config/helciny-podcasty"
#define AUDIO_DIR "/mnt/ext1/Podcasts"
#define DATA ROOT "/catalog.dat"
#define CFG ROOT "/settings"
#define IMAGE_CACHE_V2 ROOT "/images-v2"
#define AUDIO_TMP AUDIO_DIR "/HelcinyPodcasty.mp3"
#define AUDIO_PART AUDIO_DIR "/HelcinyPodcasty.part"
#define DEBUG_LOG ROOT "/playback.log"
#define SEEK_FILE ROOT "/seek"
#define POSITION_FILE ROOT "/position"
#define WORKER "/mnt/ext1/applications/HelcinyAlsaWorker.bin"
#define WORKER_LIBS "/mnt/ext1/applications/HelcinyAlsaWorker-libs"
#define BASE "http://38.19.198.69:8093/podcasts/"
#define MAXE 180
#define PAGE_SIZE 4
#define PROGRESS_Y 510
typedef struct { char feed[16],key[20],title[160],date[40],duration[16],image[80],audio[700]; } Episode;
static Episode ep[MAXE]; static int count,view,feed,page,autoplay,current_audio=-1,paused,volume=70,stop_requested,position_sec,duration_sec; static ifont *f_title,*f_body,*f_small;
static pid_t download_pid=-1; static int pending_audio=-1;
static pid_t player_pid=-1;
static char status_text[100]="";
static const char *feed_ids[]={"karlik","minecraft","otazky"};
static const char *feed_names[]={"Karlikovy minecrafticke pohadky","Minecraft pribehy na dobrou noc","Same otazky"};
static void repaint(void);
static void playback_log(const char*s){FILE*f=fopen(DEBUG_LOG,"a");if(f){fprintf(f,"%ld %s\n",(long)time(NULL),s);fflush(f);fsync(fileno(f));fclose(f);}}
static void load_last_log(void){FILE*f=fopen(DEBUG_LOG,"r");char line[180],last[180]="";if(!f)return;while(fgets(line,sizeof line,f))snprintf(last,sizeof last,"%s",line);fclose(f);last[strcspn(last,"\r\n")]=0;if(last[0])snprintf(status_text,sizeof status_text,"Diagnostika: %.75s",strchr(last,' ')?strchr(last,' ')+1:last);}

static void txt(int x,int y,int w,int h,const char*s,ifont*f,int flags){SetFont(f,BLACK);DrawTextRect(x,y,w,h,s,flags|DOTS);}
static void btn(int x,int y,int w,int h,const char*s,int dark){if(dark){FillArea(x,y,w,h,BLACK);SetFont(f_body,WHITE);}else{DrawRect(x,y,w,h,BLACK);SetFont(f_body,BLACK);}DrawTextRect(x,y+8,w,h-12,s,ALIGN_CENTER|VALIGN_MIDDLE);}
static int hit(int x,int y,int bx,int by,int bw,int bh){return x>=bx&&x<bx+bw&&y>=by&&y<by+bh;}
static void mkdirs(void){mkdir(ROOT,0777);mkdir(ROOT "/images",0777);mkdir(AUDIO_DIR,0777);}
static void migrate_image_cache(void){DIR*d;struct dirent*de;char path[400];FILE*f;if(!access(IMAGE_CACHE_V2,R_OK))return;d=opendir(ROOT "/images");if(d){while((de=readdir(d)))if(strstr(de->d_name,".jpg")){snprintf(path,sizeof path,ROOT "/images/%s",de->d_name);remove(path);}closedir(d);}f=fopen(IMAGE_CACHE_V2,"w");if(f){fputs("2\n",f);fclose(f);}}
static void save_cfg(void){FILE*f=fopen(CFG,"w");if(f){fprintf(f,"%d %d\n",autoplay,volume);fclose(f);}}
static void load_cfg(void){FILE*f=fopen(CFG,"r");if(f){fscanf(f,"%d %d",&autoplay,&volume);fclose(f);}if(volume<0||volume>100)volume=70;}
static int split(char*s,char**v,int max){int n=0;while(n<max&&(v[n]=strsep(&s,"|"))!=NULL)n++;return n;}
static int load_catalog(void){FILE*f=fopen(DATA,"r");char line[2048];count=0;if(!f)return 0;while(fgets(line,sizeof line,f)){char*p[10];int complete=strchr(line,'\n')||feof(f);if(!complete){while(fgets(line,sizeof line,f)&&!strchr(line,'\n')){}continue;}line[strcspn(line,"\r\n")]=0;if(line[0]!='E'||split(line,p,10)<8||count>=MAXE)continue;if(strncmp(p[7],"http://",7)&&strncmp(p[7],"https://",8))continue;Episode*e=&ep[count++];snprintf(e->feed,sizeof e->feed,"%s",p[1]);snprintf(e->key,sizeof e->key,"%s",p[2]);snprintf(e->title,sizeof e->title,"%s",p[3]);snprintf(e->date,sizeof e->date,"%s",p[4]);snprintf(e->duration,sizeof e->duration,"%s",p[5]);snprintf(e->image,sizeof e->image,"%s",p[6]);snprintf(e->audio,sizeof e->audio,"%s",p[7]);}fclose(f);return count;}
static void refresh(void){int rc;char cmd[1200],url[300];mkdirs();FillArea(35,95,ScreenWidth()-70,55,WHITE);txt(40,100,ScreenWidth()-80,42,"Obnovuji katalog pres WiFi...",f_small,ALIGN_LEFT);PartialUpdate(35,95,ScreenWidth()-70,55);snprintf(url,sizeof url,"%scatalog.dat",BASE);snprintf(cmd,sizeof cmd,"rm -f '%s.tmp'; (/bin/busybox wget -q -T 30 -O '%s.tmp' '%s' || /usr/bin/wget -q -T 30 -O '%s.tmp' '%s' || wget -q -T 30 -O '%s.tmp' '%s')",DATA,DATA,url,DATA,url,DATA,url);remove(DATA ".tmp");rc=DownloadTo(0,url,NULL,DATA ".tmp",30);if(rc!=NET_OK)rc=system(cmd);if(!rc&&access(DATA ".tmp",R_OK)==0)rename(DATA ".tmp",DATA);else rc=-1;if(rc)snprintf(status_text,sizeof status_text,"Obnova selhala. Zkontroluj WiFi.");else if(!load_catalog())snprintf(status_text,sizeof status_text,"Stazeny katalog je poskozeny.");else snprintf(status_text,sizeof status_text,"Katalog byl uspesne obnoven.");}
static int indices(int*out){int i,n=0,start=page*PAGE_SIZE;for(i=0;i<count;i++)if(!strcmp(ep[i].feed,feed_ids[feed])){if(n>=start&&n<start+PAGE_SIZE)out[n-start]=i;n++;}return n;}
static void fetch_image(Episode*e){char path[300],url[400],cmd[1400];struct stat st;int rc;if(!e->image[0])return;snprintf(path,sizeof path,ROOT "/images/%s.jpg",e->key);if(!stat(path,&st)&&st.st_size>200)return;remove(path);snprintf(url,sizeof url,"%s%s",BASE,e->image);remove(strcat(strcpy(cmd,path),".tmp"));rc=DownloadTo(0,url,NULL,cmd,15);if(rc!=NET_OK){snprintf(cmd,sizeof cmd,"/bin/busybox wget -q -T 15 -O '%s.tmp' '%s' && mv '%s.tmp' '%s'",path,url,path,path);system(cmd);}else rename(cmd,path);}
static void prepare_page_images(void){int ids[PAGE_SIZE],total=indices(ids),shown=total-page*PAGE_SIZE,i;if(shown>PAGE_SIZE)shown=PAGE_SIZE;for(i=0;i<shown;i++)fetch_image(&ep[ids[i]]);}
static void draw_home(void){int w=ScreenWidth(),i;txt(40,30,w-80,65,"Helciny podcasty",f_title,ALIGN_LEFT);txt(40,100,w-80,42,"Online poslech pres WiFi",f_small,ALIGN_LEFT);for(i=0;i<3;i++)btn(55,170+i*98,w-110,88,feed_names[i],0);btn(55,480,w-110,88,autoplay?"Dalsi dil: ZAPNUTO":"Dalsi dil: VYPNUTO",autoplay);btn(55,578,w-110,88,"OBNOVIT KATALOG",0);if(player_pid>0)btn(55,690,w-110,88,"NYNI HRAJE",1);if(status_text[0])txt(55,800,w-110,55,status_text,f_small,ALIGN_CENTER);}
static void draw_list(void){int w=ScreenWidth(),ids[PAGE_SIZE],total=indices(ids),shown=total-page*PAGE_SIZE,i;char s[100];if(shown>PAGE_SIZE)shown=PAGE_SIZE;txt(35,25,w-70,55,feed_names[feed],f_title,ALIGN_LEFT);snprintf(s,sizeof s,"Epizody %d-%d z %d",page*PAGE_SIZE+1,page*PAGE_SIZE+shown,total);txt(38,82,w-76,38,s,f_small,ALIGN_LEFT);for(i=0;i<shown;i++){Episode*e=&ep[ids[i]];int y=130+i*260;char path[300],meta[80];snprintf(path,sizeof path,ROOT "/images/%s.jpg",e->key);ibitmap*bm=LoadJPEG(path,250,250,100,100,1);DrawRect(40,y,250,250,BLACK);if(bm){DrawBitmap(40,y,bm);free(bm);}else remove(path);txt(320,y+25,w-360,135,e->title,f_body,ALIGN_LEFT|VALIGN_MIDDLE);snprintf(meta,sizeof meta,"%s   %s",e->duration,e->date);txt(320,y+175,w-360,45,meta,f_small,ALIGN_LEFT);DrawLine(40,y+252,w-40,y+252,BLACK);}btn(35,1180,175,80,"ZPET",0);if(player_pid>0)btn(235,1180,w-680,80,"NYNI HRAJE",1);btn(w-420,1180,175,80,"<",0);btn(w-220,1180,175,80,">",0);}
static int parse_duration(const char*s){int a=0,b=0,c=0;if(sscanf(s,"%d:%d:%d",&a,&b,&c)==3)return a*3600+b*60+c;if(sscanf(s,"%d:%d",&a,&b)==2)return a*60+b;return 0;}
static void draw_progress(void){int w=ScreenWidth(),barw=w-140,fill=duration_sec>0?(int)((long)barw*position_sec/duration_sec):0;char s[80];if(fill<0)fill=0;if(fill>barw)fill=barw;FillArea(55,PROGRESS_Y,w-110,72,WHITE);DrawRect(70,PROGRESS_Y+5,barw,28,BLACK);if(fill>2)FillArea(72,PROGRESS_Y+7,fill-2,24,BLACK);snprintf(s,sizeof s,"%d:%02d / %d:%02d",position_sec/60,position_sec%60,duration_sec/60,duration_sec%60);txt(70,PROGRESS_Y+37,barw,32,s,f_small,ALIGN_CENTER);}
static void draw_player(void){int w=ScreenWidth();char s[80],path[300];ibitmap*bm=NULL;txt(40,25,w-80,60,"Nyni hraje",f_title,ALIGN_CENTER);if(current_audio>=0){snprintf(path,sizeof path,ROOT "/images/%s.jpg",ep[current_audio].key);bm=LoadJPEG(path,240,240,100,100,1);DrawRect((w-240)/2,95,240,240,BLACK);if(bm){DrawBitmap((w-240)/2,95,bm);free(bm);}txt(50,350,w-100,135,ep[current_audio].title,f_body,ALIGN_CENTER|VALIGN_MIDDLE);}draw_progress();btn(70,600,w-140,95,paused?"POKRACOVAT":"PAUZA",paused);snprintf(s,sizeof s,"HLASITOST  %d %%",volume);txt(60,720,w-120,50,s,f_body,ALIGN_CENTER);btn(70,785,180,85,"-",0);btn(w-250,785,180,85,"+",0);btn(70,910,w-140,95,"ZASTAVIT",0);btn(70,1040,w-140,90,autoplay?"DALSI DIL: ZAPNUTO":"DALSI DIL: VYPNUTO",autoplay);btn(70,1170,w-140,85,"ZPET K EPIZODAM",0);}
static int valid_mp3(const char*path){unsigned char b[3];FILE*f=fopen(path,"rb");if(!f)return 0;if(fread(b,1,3,f)!=3){fclose(f);return 0;}fclose(f);return !memcmp(b,"ID3",3)||(b[0]==0xff&&(b[1]&0xe0)==0xe0);}
static void wake_network(void){char url[300];snprintf(url,sizeof url,"%scatalog.dat",BASE);remove(ROOT "/network.tmp");DownloadTo(0,url,NULL,ROOT "/network.tmp",20);remove(ROOT "/network.tmp");}
static void poll_player(void);
static void start_player(void){char command[1200],vol[8];if(player_pid>0)return;snprintf(vol,sizeof vol,"%d",volume);snprintf(command,sizeof command,"exec env LD_LIBRARY_PATH='/ebrmain/lib:/ebrmain/cramfs/lib:/usr/local/lib:/usr/lib:/lib:%s' '%s' '%s' '%s' >>'%s' 2>&1",WORKER_LIBS,WORKER,AUDIO_TMP,vol,DEBUG_LOG);stop_requested=0;paused=0;position_sec=0;duration_sec=current_audio>=0?parse_duration(ep[current_audio].duration):0;remove(SEEK_FILE);remove(POSITION_FILE);player_pid=fork();if(player_pid==0){execl("/bin/sh","sh","-c",command,(char*)NULL);_exit(127);}if(player_pid<0){snprintf(status_text,sizeof status_text,"Prehravac nelze spustit.");repaint();return;}playback_log("05 ALSA player started");view=2;repaint();SetWeakTimer("podcast-player",poll_player,500);}
static void finish_download(void){int status;char msg[120];struct stat st;pid_t done=waitpid(download_pid,&status,WNOHANG);if(done==0){SetWeakTimer("podcast-download",finish_download,1000);return;}download_pid=-1;if(done<0||!WIFEXITED(status)||WEXITSTATUS(status)||stat(AUDIO_PART,&st)||st.st_size<1024||!valid_mp3(AUDIO_PART)){remove(AUDIO_PART);playback_log("03 download failed");snprintf(status_text,sizeof status_text,"Epizodu se nepodarilo nacist.");repaint();return;}snprintf(msg,sizeof msg,"03 valid mp3 bytes=%ld",(long)st.st_size);playback_log(msg);remove(AUDIO_TMP);if(rename(AUDIO_PART,AUDIO_TMP)){playback_log("04 rename failed");snprintf(status_text,sizeof status_text,"Docasny soubor nelze ulozit.");repaint();return;}playback_log("04 local file ready");current_audio=pending_audio;start_player();}
static void play_index(int idx){char cmd[1900];if(idx<0||idx>=count||download_pid>0)return;if(player_pid>0){snprintf(status_text,sizeof status_text,"Nejprve zastav prehravanou epizodu.");repaint();return;}FillArea(35,78,ScreenWidth()-70,48,WHITE);txt(38,82,ScreenWidth()-76,40,"Pripojuji WiFi a stahuji epizodu...",f_small,ALIGN_LEFT);FullUpdate();wake_network();remove(DEBUG_LOG);playback_log("01 download start");remove(AUDIO_PART);snprintf(cmd,sizeof cmd,"(/bin/busybox wget -q -T 300 -O '%s' '%s' || /usr/bin/wget -q -T 300 -O '%s' '%s' || wget -q -T 300 -O '%s' '%s') 2>>'%s'",AUDIO_PART,ep[idx].audio,AUDIO_PART,ep[idx].audio,AUDIO_PART,ep[idx].audio,DEBUG_LOG);pending_audio=idx;download_pid=fork();if(download_pid==0){execl("/bin/sh","sh","-c",cmd,(char*)NULL);_exit(127);}if(download_pid<0){playback_log("02 fork failed");snprintf(status_text,sizeof status_text,"Stahovani nelze spustit.");repaint();return;}playback_log("02 download process started");SetWeakTimer("podcast-download",finish_download,1000);}
static void play_episode(int selected){int ids[PAGE_SIZE],total=indices(ids);if(selected<0||selected>=PAGE_SIZE||page*PAGE_SIZE+selected>=total)return;play_index(ids[selected]);}
static int next_episode(void){int i;if(current_audio<0)return -1;for(i=current_audio-1;i>=0;i--)if(!strcmp(ep[i].feed,ep[current_audio].feed))return i;return -1;}
static void poll_player(void){int status,pos,total,old=position_sec;pid_t done;FILE*f;if(player_pid<=0)return;f=fopen(POSITION_FILE,"r");if(f){if(fscanf(f,"%d %d",&pos,&total)==2){position_sec=pos;if(total>0)duration_sec=total;}fclose(f);}if(view==2&&position_sec!=old){draw_progress();PartialUpdate(55,PROGRESS_Y,ScreenWidth()-110,72);}done=waitpid(player_pid,&status,WNOHANG);if(done==0){SetWeakTimer("podcast-player",poll_player,500);return;}player_pid=-1;paused=0;if(!stop_requested&&done>0&&WIFEXITED(status)&&WEXITSTATUS(status)==0&&autoplay){int next=next_episode();if(next>=0){snprintf(status_text,sizeof status_text,"Nacitam nasledujici dil...");play_index(next);return;}}if(view==2){snprintf(status_text,sizeof status_text,stop_requested?"Prehravani zastaveno.":"Epizoda dohrala.");view=1;repaint();}}
static void repaint(void){ClearScreen();if(view==0)draw_home();else if(view==1)draw_list();else draw_player();FullUpdate();}
static void seek_to(int x){int w=ScreenWidth();FILE*f;if(duration_sec<=0)return;position_sec=(int)((long)(x-70)*duration_sec/(w-140));if(position_sec<0)position_sec=0;if(position_sec>duration_sec)position_sec=duration_sec;f=fopen(SEEK_FILE,"w");if(f){fprintf(f,"%d\n",position_sec);fclose(f);}draw_progress();PartialUpdate(55,PROGRESS_Y,w-110,72);}
static void touch(int x,int y){int w=ScreenWidth(),i;if(view==0){for(i=0;i<3;i++)if(hit(x,y,55,170+i*98,w-110,88)){feed=i;page=0;view=1;prepare_page_images();repaint();return;}if(hit(x,y,55,480,w-110,88)){autoplay=!autoplay;save_cfg();repaint();}else if(hit(x,y,55,578,w-110,88)){refresh();repaint();}else if(player_pid>0&&hit(x,y,55,690,w-110,88)){view=2;repaint();}}else if(view==1){if(y>=130&&y<1170&&x>=40&&x<w-40&&(y-130)%260<250){i=(y-130)/260;if(i<PAGE_SIZE)play_episode(i);}else if(hit(x,y,35,1165,190,110)){view=0;repaint();}else if(player_pid>0&&hit(x,y,235,1165,w-680,110)){view=2;repaint();}else if(hit(x,y,w-430,1165,190,110)&&page>0){page--;prepare_page_images();repaint();}else if(hit(x,y,w-230,1165,200,110)){int ids[PAGE_SIZE];if((page+1)*PAGE_SIZE<indices(ids)){page++;prepare_page_images();repaint();}}}else{if(hit(x,y,70,PROGRESS_Y-10,w-140,80)&&player_pid>0){seek_to(x);}else if(hit(x,y,70,600,w-140,95)&&player_pid>0){kill(player_pid,SIGUSR1);paused=!paused;repaint();}else if(hit(x,y,70,785,180,85)&&player_pid>0&&volume>0){volume-=10;kill(player_pid,SIGHUP);save_cfg();repaint();}else if(hit(x,y,w-250,785,180,85)&&player_pid>0&&volume<100){volume+=10;kill(player_pid,SIGUSR2);save_cfg();repaint();}else if(hit(x,y,70,910,w-140,95)&&player_pid>0){stop_requested=1;kill(player_pid,SIGTERM);}else if(hit(x,y,70,1040,w-140,90)){autoplay=!autoplay;save_cfg();repaint();}else if(hit(x,y,70,1170,w-140,85)){view=1;repaint();}}}
static int handler(int type,int p1,int p2){if(type==EVT_INIT){f_title=OpenFont(DEFAULTFONTB,42,1);f_body=OpenFont(DEFAULTFONT,30,1);f_small=OpenFont(DEFAULTFONT,23,1);mkdirs();migrate_image_cache();load_cfg();load_catalog();load_last_log();repaint();}else if(type==EVT_REPAINT)repaint();else if(type==EVT_POINTERUP)touch(p1,p2);else if(type==EVT_KEYDOWN&&p1==IV_KEY_BACK){if(view==2){view=1;repaint();}else if(view){view=0;repaint();}else CloseApp();}else if(type==EVT_EXIT){if(player_pid>0)kill(player_pid,SIGTERM);CloseFont(f_title);CloseFont(f_body);CloseFont(f_small);}return 0;}
int main(void){InkViewMain(handler);return 0;}
